### PR TITLE
Update to Minecraft 1.12

### PR DESCRIPTION
**Pull request by magneticflux-**
I have tested to make sure that it launches, but I have not tested with another person yet.
Closes #16

### CODE REVIEW

**Comment by magneticflux-** [comment]
Additionally @zsawyer, you can change the active branch on GitHub to "QnD-MC_JNA" in the Settings page since that seems to be the most developed-on branch.

**Comment by magneticflux-** [comment]
Hooray, I fixed the CI!

**Comment by zsawyer** [comment]
Please don't up the min java version if you don't have to as it breaks MC for a lot of MAC users (yes there are quite a number that still are on 1.6). I don't want another flood of Apple user reporting issues just because Apple has that vendetta against Oracle going on.

Regarding the CI: 
https://forgegradle.readthedocs.io/en/latest/reference/tasks/

**Comment by magneticflux-** [comment]
@zsawyer MC 1.12 [requires Java 8](https://twitter.com/Dinnerbone/status/847408242233704448), so users must have it to run the game, period. In addition, it actually comes bundled with Minecraft for macOS compatibility. The CI stuff couldn't find the task because it was being run outside of the project directory. I just added a `cd` before running the Gradle task. I also updated the caching from Travis CI's Gradle documentation.

**Comment by Robijnvogel** [comment]
So why isn't this merged and released yet?
I just updated most of this (except travis) myself as well, just to find that it had already done by someone else. :P

**Comment by jeremyprz** [comment]
Does anyone have a download-link of a 1.12.2 binary? Would like to start using, but looks like the official release is being neglected. Might try to self build if I can figure it out.

**Comment by magneticflux-** [comment]
@jeremyprz AFAIK my fork for 1.12 should keep working with 1.12.2. I haven't played/modded in a while due to other obligations though.

To build it (I don't have the jar with me currently), you don't even need an IDE. Just run 
```Gradle
./gradlew SetupCIWorkspace build
```
and hunt through the build outputs for the jar file.

**Pull request merged**
